# Generated by Django 5.0.6 on 2024-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
