# Generated by Django 5.0.6 on 2024-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_item_colors_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='html',
            field=models.CharField(default='#000000', max_length=7, verbose_name='HTML код'),
        ),
    ]
